# run with 
# slm-run --config config.ini -f queries/recurse/tape_update.sparql --debug

PREFIX ex: <http://example.org/>
prefix ggf: <http://ggf.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?head ?cell ?new_value ?state WHERE {
  BIND(ggf:LOAD("./data/tape.trig") AS ?tape)
  BIND("""
    PREFIX ex: <http://example.org/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    DELETE {
        ex:head ex:at ?cell .
        ex:head ex:state ?current_state .
        ?cell ex:value ?current_value .  }  
    INSERT {
      ex:head ex:at ?next_cell .
      ex:head ex:state ?new_state .
      ?cell ex:value ?new_value .  }
    WHERE {
      ex:head ex:at ?cell ;
              ex:state ?current_state .
      ?cell ex:value ?current_value ;
            ex:right ?next_cell .
      ?next_cell ex:value ?next_value .
      ?t ex:fromState ?current_state ;
          ex:read ?current_value ;
          ex:toState ?new_state ;
          ex:write ?new_value ;
          ex:move 'R' .
    } 
  """ AS ?query_str)

  BIND(ggf:RECURSE-UPDATE(?query_str, ?tape,10) AS ?final_graph)

  GRAPH ?final_graph { 
    {
       ex:head ex:at ?head .
       ex:head ex:state ?state .
    } union {
      ?cell ex:value ?new_value .
    }

  }   
}
