# slm-run --config config.ini -f queries/debug_wikidata_villages.sparql --debug
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?village ?villageLabel WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    SELECT ?village ?villageLabel WHERE {
      VALUES ?villageLabel {
        "Rezé"@fr
        "Saint-Herblain"@fr
        "Orvault"@fr
        "Vertou"@fr
        "Carquefou"@fr
        "Sainte-Luce-sur-Loire"@fr
        "Bouguenais"@fr
        "Saint-Sébastien-sur-Loire"@fr
        "La Chapelle-sur-Erdre"@fr
        "Sautron"@fr
        "Indre"@fr
        "Saint-Jean-de-Boiseau"@fr
        "Bouaye"@fr
        "Basse-Goulaine"@fr
        "Haute-Goulaine"@fr
        "Thouaré-sur-Loire"@fr
        "Les Sorinières"@fr
        "Treillières"@fr
        "La Montagne"@fr
      }
      ?village rdfs:label ?villageLabel ;
               wdt:P31/wdt:P279* wd:Q532 .
    }
  }
}