# run with slm-run --config config.ini -f queries/directory_recurse.sparql --debug


PREFIX ex: <http://example.org/>
SELECT ?p (MAX(?s2) AS ?max_s)  WHERE {
    ## init recursion
    BIND(ex:SLM-FILE("./SPARQLLM") AS ?root)
    BIND(ex:SLM-READDIR(?root,?root) AS ?ginit)
    BIND("""
    PREFIX ex: <http://example.org/>
    CONSTRUCT {
        ?p ex:has_path ?p1 .
        ?p1 ex:has_type ?t1.
        ?p1 ex:has_size ?s1 .
        ?new ex:has_path ?p2 .
        ?p2 ex:has_type ?t2.
        ?p2 ex:has_size ?s2 .

    } WHERE {
        graph ?gin {
          {
            ?p ex:has_path ?p1 .
            ?p1 ex:has_type ?t1 .
            ?p1 ex:has_size ?s1 .
            FILTER (str(?t1)="file")
          } UNION {
            ?p ex:has_path ?p1 .
            ?p1 ex:has_type ?t1 .
            ?p1 ex:has_size ?s1 .
            FILTER (str(?t1)="directory")
            BIND(ex:SLM-READDIR(?p1,?p1) as ?rdir)
            OPTIONAL {
                GRAPH ?rdir {
                    ?new ex:has_path ?p2 .
                    ?p2 ex:has_type ?t2.
                    ?p2 ex:has_size ?s2 .
                }
            }}
        }
    } """ AS ?query_str)
    BIND(ex:SLM-RECURSE(?query_str,?ginit,3) AS ?out)
    GRAPH ?out {
        ?p ex:has_path ?p2 .
        ?p2 ex:has_type ?t2.
        ?p2 ex:has_size ?s2 .
     } 
}
        
