# run with:
# slm-run --config config.ini -f queries/mcp/github-issues-udf.sparql --debug

PREFIX ex: <http://example.org/>
PREFIX schema: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?pr ?title  WHERE {
  BIND(ex:SLM-GITHUB("openwrt", "openwrt", "pulls", "", 20) AS ?gGithub)
  GRAPH ?gGithub {
      ?repo a schema:Repository ;
          schema:hasPart ?pr .
    OPTIONAL { ?pr schema:name ?title }
  }
} LIMIT 5
