# run with:
# slm-run --config config.ini -f queries/mcp/mcp_github.sparql --debug

PREFIX slm:    <http://example.org/>
PREFIX schema: <https://schema.org/>
PREFIX prov:   <http://www.w3.org/ns/prov#>

SELECT  ?pr ?title ?t  WHERE {
  # Appel tool -> graph blank node contenant le fragment JSON-LD (repo + hasPart)
  BIND( slm:SLM-MCP-TOOL("github","github.pullRequests.list",
        slm:SLM-OBJ("owner","openwrt","repo","openwrt","state","open","limit",10)) AS ?g )

  GRAPH ?g {
    ?repo a schema:Repository ;
          schema:hasPart ?pr .
    OPTIONAL { ?pr schema:name ?title }

    ?g prov:generatedAtTime ?t ;
  }
}
ORDER BY DESC(?t)
LIMIT 5

