# run with slm-run -f queries/filesystem/readfile.sparql --debug

PREFIX ggf: <http://ggf.org/>
SELECT ?uri ?t
WHERE {
    BIND(ggf:SLM-FILE("./data/zenodo.html") AS ?uri)
    BIND(ggf:SLM-READHTMLFILE(?uri,100) AS ?t)
}