# run with
# slm-run --config config.ini -f queries/filesystem/simple-csv.sparql --debug
PREFIX ggf: <http://ggf.org/>
PREFIX ex: <http://example.org/>
SELECT ?x ?z WHERE {
    BIND(ggf:SLM-FILE("./data/results.csv") as ?value)
    BIND(ggf:SLM-CSV(?value) AS ?g)
    graph ?g {
        ?x ex:city ?z .
    }
}
