# slm-run --config config.ini -f queries/hello_neuro_nouri.sparql --debug

PREFIX ggf: <http://example.org/>
PREFIX schema: <http://schema.org/>

SELECT ?msg {
    BIND("""Say Hello to the neuro-symbolic world:
    Return *ONLY* a JSON-LD object of type `Event` in the following format:
    {
      "@context": "http://schema.org/",
      "@type": "Event",
      "message": "text",
    }
    """ AS ?prompt)
    BIND(ggf:LLM(?prompt) AS ?g)
     GRAPH ?g {
        ?root a schema:Event. 
        ?root schema:message ?msg .
     }
}