# slm-run --config config.ini -f queries/LLM/hello_neuro.sparql --debug

PREFIX ggf: <http://ggf.org/>
PREFIX schema: <https://schema.org/>

SELECT ?msg {
    BIND("""Say Hello to the neuro-symbolic world:
    Return *ONLY* a JSON-LD object of type `Event` in the following format:
    {
      "@context": "https://schema.org/",
      "@type": "Event",
      "message": "text",
    }
    """ AS ?prompt)
    BIND(ggf:LLM(?prompt) AS ?g)
     GRAPH ?g {
        ?root a schema:Event. 
        OPTIONAL { ?root schema:message ?msg . }
     }
}