# slm-run --config config.ini -f queries/LLM/simple-groq.sparql --debug

PREFIX wdt: <http://www.wikidata.org/prop/direct/>    # Propriétés directes (ex. wdt:P31 pour "instance de")
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>  
PREFIX ex: <http://example.org/>
PREFIX schema: <https://schema.org/>
PREFIX ggf: <http://ggf.org/>

select * {
    # strange only 85 raise an error...
    BIND(ggf:SLM-FILE("./data/events/event_85.txt") AS ?uri)
    BIND(ggf:SLM-READFILE(?uri) AS ?page)

    BIND(CONCAT("""
    Extract from the text below the date and the name of the event.

    Return **only** a JSON-LD object of type `Event` using the `http://schema.org/` context, in the following format:

    {
      "@context": "https://schema.org/",
      "@type": "Event",
      "startDate": "2025-01-01",
      "name": "Sample Event Name"
    }

    - Replace the example values with the actual event date and event name.
    - The output must be valid JSON-LD with no explanations, comments, or Markdown formatting.
    - Output **only** the JSON object.

    Here is the text to analyze:
    <text>""",STR(?page),"</text>") AS ?prompt)
    BIND(ggf:SLM-LLMGRAPH_GROQ(?prompt,?uri) AS ?g)
     GRAPH ?g {
        ?uri ex:has_schema_type ?root . 
        ?root a schema:Event. 
        ?root schema:startDate ?date.
        ?root schema:name ?name
     }
}