# slm-run --config config.ini -f queries/LLM/simple_llm.sparql --debug

PREFIX wdt: <http://www.wikidata.org/prop/direct/>    # Propriétés directes (ex. wdt:P31 pour "instance de")
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>  
PREFIX ex: <http://example.org/>
PREFIX schema: <https://schema.org/>
PREFIX ggf: <http://ggf.org/>

SELECT * {
    BIND("""From the text :
          Dance in Portoroz: A slovenian dance show highlighting the 
            talent of choreographers and dancers. Come and enjoy this event!
          Date: 28 April 2025
          City: Portoroz
          Category: Dance

    Return *ONLY* a JSON-LD object of type `Event` in the following format:
    {
      "@context": "https://schema.org/",
      "@type": "Event",
      "startDate": "2025-01-01",
      "city": "simple city name"
    }
    """ AS ?prompt)
    BIND(<http://example.org/e1> AS ?uri)
    BIND(ggf:SLM-LLMGRAPH_GROQ(?prompt,?uri) AS ?g)
     GRAPH ?g {
#        ?uri ex:has_schema_type ?bn . 
#        ?root a schema:Event. 
        ?root schema:startDate ?date.
        ?root schema:city ?city
        FILTER(?city = "Portoroz") 
     }
}